# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            ddeconde.github.io
tagline:          A modest pied-&#224-terre on the web.
description:      A very basic personal site.
url:              http://getpoole.com

author:
  name:           David DeConde
  url:            http://ddeconde.github.io

paginate:         1

# Custom vars
version:          0.1.0

github:
  repo:           https://github.com/ddeconde
