# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Ddeconde
tagline:          'A site template based on the Lanyon Jekyll theme'
description:      'A very basic and minimal personal site.'
url:              http://ddeconde.guthub.io

author:
  name:           'ddeconde'
  url:            https://twitter.com/

paginate:         5

# Custom vars
version:          0.1.0

github:
  repo:           https://github.com/ddeconde/ddeconde.github.io
